"use client"
import { FormEvent,useState } from "react"
import { useRouter } from "next/navigation"
import { CheckCircle2,LoaderCircle,ShieldCheck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
export function AssignmentSubmit({id}:{id:string}){return <InlinePost endpoint={`lms/assignments/${id}/submit`} field="text" placeholder="Submission text" label="Submit assignment" transform={v=>({text:v,attachmentUrls:[]})}/>}
export function GradeSubmission({id}:{id:string}){const router=useRouter(),[busy,setBusy]=useState(false);async function grade(){const score=prompt("Score");if(score===null)return;const feedback=prompt("Feedback (optional)")??"";setBusy(true);const r=await fetch(`/api/backend/lms/submissions/${id}/grade`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({score:Number(score),feedback:feedback||undefined})});setBusy(false);if(!r.ok){const b=await r.json().catch(()=>null);return alert(b?.message??"Grading failed")}router.refresh()}return <Button size="sm" variant="outline" disabled={busy} onClick={grade}>{busy?<LoaderCircle className="animate-spin"/>:<CheckCircle2/>}Grade</Button>}
export function ThesisAction({id,action}:{id:string;action:"approve"|"reject"|"start"|"complete_revision"}){const router=useRouter(),[busy,setBusy]=useState(false);async function run(){if(!confirm(`${action.replace("_"," ")} this thesis?`))return;setBusy(true);const r=await fetch(`/api/backend/research/theses/${id}/supervisor-action`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});setBusy(false);if(!r.ok){const b=await r.json().catch(()=>null);return alert(b?.message??"Action failed")}router.refresh()}return <Button size="sm" variant="outline" disabled={busy} onClick={run}>{busy?<LoaderCircle className="animate-spin"/>:<ShieldCheck/>}{action.replace("_"," ")}</Button>}
export function ComplaintAction({id,status}:{id:string;status:string}){const router=useRouter(),[busy,setBusy]=useState(false);async function run(){const action=status==="submitted"?"start_review":status==="under_review"?"resolve":"close";const assignedToUserId=action==="start_review"?prompt("Assignee user ID"):undefined;if(action==="start_review"&&!assignedToUserId)return;const resolution=action==="resolve"?prompt("Resolution"):undefined;if(action==="resolve"&&!resolution)return;setBusy(true);const r=await fetch(`/api/backend/engagement/complaints/${id}/action`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,assignedToUserId,resolution})});setBusy(false);if(!r.ok){const b=await r.json().catch(()=>null);return alert(b?.message??"Action failed")}router.refresh()}return <Button size="sm" variant="outline" disabled={busy||status==="closed"} onClick={run}>{busy?<LoaderCircle className="animate-spin"/>:<CheckCircle2/>}{status==="submitted"?"Review":status==="under_review"?"Resolve":"Close"}</Button>}
export function AlumniVerify({id,status}:{id:string;status:string}){const router=useRouter(),[busy,setBusy]=useState(false);async function run(){setBusy(true);const r=await fetch(`/api/backend/engagement/alumni/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:status==="verified"?"suspended":"verified"})});setBusy(false);if(!r.ok){const b=await r.json().catch(()=>null);return alert(b?.message??"Action failed")}router.refresh()}return <Button size="sm" variant="outline" disabled={busy} onClick={run}>{busy?<LoaderCircle className="animate-spin"/>:<ShieldCheck/>}{status==="verified"?"Suspend":"Verify"}</Button>}
function InlinePost({endpoint,field,placeholder,label,transform}:{endpoint:string;field:string;placeholder:string;label:string;transform:(v:string)=>unknown}){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("");async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,v=new FormData(form).get(field)?.toString().trim();if(!v)return;setBusy(true);setError("");const r=await fetch(`/api/backend/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(transform(v))});const b=await r.json().catch(()=>null) as {message?:string}|null;setBusy(false);if(!r.ok)return setError(b?.message??"Action failed");form.reset();router.refresh()}return <form onSubmit={send} className="space-y-2"><div className="flex gap-2"><Input name={field} placeholder={placeholder}/><Button disabled={busy}>{busy&&<LoaderCircle className="animate-spin"/>}{label}</Button></div>{error&&<p className="text-sm text-destructive">{error}</p>}</form>}
