"use client"
import { FormEvent, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { API_ENDPOINTS } from "@/lib/api-endpoints"
import { apiResponseRequest } from "@/lib/http-client"
type Item = { _id: string; code?: string; title?: string; name?: string; academicBatch?: { _id: string } | string; user?: { firstName: string; lastName: string }; employeeId?: string }
const css = "h-9 w-full rounded-lg border bg-background px-3 text-sm"
export function FacultyAllocationForm({ teachers, courses, semesters, batches, sections }: { teachers: Item[]; courses: Item[]; semesters: Item[]; batches: Item[]; sections: Item[] }) {
  const router = useRouter(), [batchId, setBatchId] = useState(""), [loading, setLoading] = useState(false), [error, setError] = useState("")
  const available = useMemo(() => sections.filter((item) => (typeof item.academicBatch === "string" ? item.academicBatch : item.academicBatch?._id) === batchId), [batchId, sections])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const selected = available.find((item) => item._id === form.get("sectionId")); setLoading(true); setError(""); const response = await apiResponseRequest(API_ENDPOINTS.academics.offerings, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ courseId: form.get("courseId"), semesterId: form.get("semesterId"), teacherId: form.get("teacherId"), academicBatchId: batchId, section: selected?.code, capacity: Number(form.get("capacity")), deliveryMode: form.get("deliveryMode") }) }); const body = await response.json<{ message?: string }>(); setLoading(false); if (!response.ok) return setError(body.message || "Course could not be allocated"); router.push("/dashboard/faculty?tab=allocations"); router.refresh() }
  const select = (name: string, label: string, items: Item[], render: (item: Item) => string) => <div><Label>{label}</Label><select name={name} className={css} required defaultValue=""><option value="" disabled>Select {label.toLowerCase()}</option>{items.map((item) => <option key={item._id} value={item._id}>{render(item)}</option>)}</select></div>
  return <form onSubmit={submit} className="grid gap-5 sm:grid-cols-2">{select("teacherId", "Faculty member", teachers, (item) => `${item.employeeId} · ${item.user?.firstName} ${item.user?.lastName}`)}{select("semesterId", "Semester", semesters, (item) => `${item.code} · ${item.name}`)}<div><Label>Academic batch</Label><select className={css} required value={batchId} onChange={(event) => setBatchId(event.target.value)}><option value="" disabled>Select batch</option>{batches.map((item) => <option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></div>{select("sectionId", "Section", available, (item) => `${item.code} · ${item.name}`)}{select("courseId", "Course", courses, (item) => `${item.code} · ${item.title}`)}<div><Label>Capacity</Label><Input name="capacity" type="number" min={1} max={1000} defaultValue={60} required /></div><div><Label>Delivery mode</Label><select name="deliveryMode" className={css}><option value="in_person">In person</option><option value="online">Online</option><option value="hybrid">Hybrid</option></select></div>{error && <p className="text-sm text-destructive sm:col-span-2">{error}</p>}<div className="sm:col-span-2"><Button type="submit" disabled={loading}>{loading ? "Allocating…" : "Allocate course"}</Button></div></form>
}
