import { AppError } from "../../utils/AppError";
import { toObjectId } from "../../utils/mongo";
import { AcademicBatchModel } from "../academic-batch/academicBatch.model";
import { AcademicSectionModel } from "../academic-section/academicSection.model";
import { TeacherModel } from "../teacher/teacher.model";
import { FacultyAdvisingModel } from "./facultyAdvising.model";

const populate = [{ path: "teacher", select: "employeeId designation user", populate: { path: "user", select: "firstName lastName email avatarUrl" } }, { path: "academicBatch", select: "code name program" }, { path: "academicSection", select: "code name capacity enrolledCount" }];
export async function list(query: Record<string, unknown>) { const filter: Record<string, unknown> = {}; if (query.teacherId) filter.teacher = toObjectId(String(query.teacherId)); if (query.academicBatchId) filter.academicBatch = toObjectId(String(query.academicBatchId)); if (query.status) filter.status = query.status; let request = FacultyAdvisingModel.find(filter).sort({ createdAt: -1 }); for (const item of populate) request = request.populate(item); return request.lean(); }
export async function create(actorId: string, input: Record<string, unknown>) { const teacherId = toObjectId(String(input.teacherId)), batchId = toObjectId(String(input.academicBatchId)), sectionId = toObjectId(String(input.academicSectionId)); const [teacher, batch, section] = await Promise.all([TeacherModel.findOne({ _id: teacherId, status: "active" }), AcademicBatchModel.findOne({ _id: batchId, status: "active" }), AcademicSectionModel.findOne({ _id: sectionId, academicBatch: batchId, status: "active" })]); if (!teacher || !batch || !section) throw new AppError(400, "Active teacher, batch, and matching section are required"); if (await FacultyAdvisingModel.exists({ academicSection: sectionId, status: "active" })) throw new AppError(409, "This section already has an active advisor"); const { teacherId: _, academicBatchId: __, academicSectionId: ___, ...data } = input; return FacultyAdvisingModel.create({ ...data, teacher: teacherId, academicBatch: batchId, academicSection: sectionId, assignedBy: toObjectId(actorId) }); }
export async function end(id: string) { const assignment = await FacultyAdvisingModel.findOne({ _id: toObjectId(id), status: "active" }); if (!assignment) throw new AppError(404, "Active advising assignment not found"); assignment.status = "ended"; assignment.endsAt = new Date(); await assignment.save(); return assignment; }
