import Link from "next/link"
import { Bell, Mail, Megaphone, MessageCircle, Plus } from "lucide-react"
import { ReadNotification } from "@/components/communication-actions"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { authenticatedRequest } from "@/lib/auth"

type Person = { _id: string; firstName: string; lastName: string; email: string }
type Notice = { _id: string; title: string; body: string; category: string; status: string; publishAt: string; expiresAt?: string; audienceRoles: { _id: string; code: string; name: string }[]; createdBy: Person }
type Conversation = { _id: string; subject?: string; type: string; participants: Person[]; lastMessageAt: string }
type Notification = { _id: string; channel: string; type: string; title: string; body: string; status: string; createdAt: string }

export default async function CommunicationPage() {
  let notices: Notice[] = [], conversations: Conversation[] = [], notifications: Notification[] = [], error = ""
  try { const data = await Promise.all([authenticatedRequest<{ notices: Notice[] }>("/communication/notices"), authenticatedRequest<{ conversations: Conversation[] }>("/communication/conversations"), authenticatedRequest<{ items: Notification[] }>("/communication/notifications?limit=20")]); notices = data[0].data.notices; conversations = data[1].data.conversations; notifications = data[2].data.items } catch (cause) { error = cause instanceof Error ? cause.message : "Communication data unavailable" }
  const unread = notifications.filter(item => item.status !== "read").length
  return <div className="mx-auto max-w-[1600px] space-y-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-medium text-primary">Connected campus</p><h1 className="mt-1 text-3xl font-bold">Communication</h1><p className="mt-1 text-sm text-muted-foreground">Notices, conversations, and delivery notifications in one workspace.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" render={<Link href="/dashboard/communication/notices/new" />}><Megaphone />New notice</Button><Button render={<Link href="/dashboard/communication/conversations/new" />}><Plus />New conversation</Button><Button variant="outline" render={<Link href="/dashboard/communication/notifications/new" />}><Mail />Dispatch</Button></div></div>
    {error && <p className="rounded-xl bg-destructive/10 p-4 text-destructive">{error}</p>}
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Megaphone />} value={notices.length} label="Visible notices" /><Metric icon={<MessageCircle />} value={conversations.length} label="Conversations" /><Metric icon={<Bell />} value={unread} label="Unread notifications" /></div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader><CardTitle>Notice board</CardTitle></CardHeader><CardContent className="space-y-4">{notices.length === 0 && <Empty text="No notices are available." />}{notices.map(item => <article key={item._id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.publishAt).toLocaleString()} · {item.createdBy?.firstName} {item.createdBy?.lastName}</p></div><div className="flex gap-1"><Badge variant="outline" className="capitalize">{item.category}</Badge><Badge variant={item.status === "published" ? "secondary" : "outline"}>{item.status}</Badge></div></div><p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{item.body}</p>{item.audienceRoles.length > 0 && <div className="mt-3 flex flex-wrap gap-1">{item.audienceRoles.map(role => <Badge key={role._id} variant="secondary">{role.name}</Badge>)}</div>}</article>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Conversations</CardTitle></CardHeader><CardContent className="space-y-3">{conversations.length === 0 && <Empty text="No conversations yet." />}{conversations.map(item => <Link href={`/dashboard/communication/conversations/${item._id}`} key={item._id} className="block rounded-xl border p-4 transition-colors hover:bg-muted/50"><div className="flex justify-between gap-3"><div><p className="font-semibold">{item.subject || item.participants.map(person => `${person.firstName} ${person.lastName}`).join(", ")}</p><p className="mt-1 text-xs text-muted-foreground">{item.participants.length} participants · {item.type}</p></div><p className="text-xs text-muted-foreground">{new Date(item.lastMessageAt).toLocaleDateString()}</p></div></Link>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Notification inbox</CardTitle></CardHeader><CardContent className="space-y-3">{notifications.length === 0 && <Empty text="No notifications yet." />}{notifications.map(item => <div key={item._id} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><p className="font-semibold">{item.title}</p><Badge variant={item.status === "read" ? "outline" : "secondary"}>{item.status}</Badge><Badge variant="outline">{item.channel}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.body}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()} · {item.type}</p></div>{item.status !== "read" && <ReadNotification id={item._id} />}</div>)}</CardContent></Card>
  </div>
}
function Metric({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <Card><CardContent className="p-5"><div className="text-primary [&_svg]:size-5">{icon}</div><p className="mt-4 text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></CardContent></Card> }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</p> }
