import Link from "next/link"
import {ArrowLeft} from "lucide-react"
import {AssignmentSubmit,GradeSubmission} from "@/components/advanced-actions"
import {Badge} from "@/components/ui/badge"
import {Button} from "@/components/ui/button"
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card"
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table"
import {authenticatedRequest} from "@/lib/auth"
type Submission={_id:string;student:{studentId:string;user:{firstName:string;lastName:string}};text?:string;submittedAt:string;score?:number;status:string}
export default async function Page({params}:{params:Promise<{id:string}>}){const{id}=await params;let submissions:Submission[]=[],manager=true,error="";try{submissions=(await authenticatedRequest<{submissions:Submission[]}>(`/lms/assignments/${id}/submissions`)).data.submissions}catch(c){manager=false;error=c instanceof Error?c.message:"Submission data unavailable"}return <div className="mx-auto max-w-5xl space-y-6"><Button variant="ghost" render={<Link href="/dashboard/lms"/>}><ArrowLeft/>LMS</Button><div><h1 className="text-3xl font-bold">Assignment workspace</h1><p className="mt-1 text-sm text-muted-foreground">Submit student work or review and grade the class roster.</p></div>{!manager&&<Card><CardHeader><CardTitle>Submit your work</CardTitle></CardHeader><CardContent><AssignmentSubmit id={id}/><p className="mt-3 text-xs text-muted-foreground">{error}</p></CardContent></Card>}{manager&&<Card><CardHeader><CardTitle>Submissions ({submissions.length})</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Submission</TableHead><TableHead>Submitted</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{submissions.map(x=><TableRow key={x._id}><TableCell><p className="font-medium">{x.student?.user?.firstName} {x.student?.user?.lastName}</p><p className="text-xs text-muted-foreground">{x.student?.studentId}</p></TableCell><TableCell className="max-w-sm whitespace-pre-wrap">{x.text||"Attachment submission"}</TableCell><TableCell>{new Date(x.submittedAt).toLocaleString()}</TableCell><TableCell><Badge variant={x.status==="graded"?"secondary":"outline"}>{x.status}{x.score!==undefined?` · ${x.score}`:""}</Badge></TableCell><TableCell><GradeSubmission id={x._id}/></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>}
