import Link from "next/link"
import { Building2, FolderTree, List, Users } from "lucide-react"
import { PaginationLinks } from "@/components/pagination-links"
import { StudentStatusBadge } from "@/components/student-status"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { API_ENDPOINTS, withQuery } from "@/lib/api-endpoints"
import { authenticatedRequest } from "@/lib/auth"
import type { AcademicList } from "@/lib/academic-types"
import type { StudentListData } from "@/lib/student-types"
type Department = { _id: string; code: string; name: string }
type Batch = { _id: string; code: string; name: string; program: { _id: string; code: string; name: string } }
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value }
export default async function StudentStructurePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const departmentId = first(raw.departmentId) ?? ""; const batchId = first(raw.batchId) ?? ""; const section = first(raw.section) ?? ""; const page = Math.max(1, Number(first(raw.page)) || 1)
  const departments = (await authenticatedRequest<AcademicList>(withQuery(API_ENDPOINTS.academics.departments, { status: "active", limit: 100 }))).data.items as Department[]
  let batches: Batch[] = []; let students: StudentListData | null = null
  if (departmentId) batches = (await authenticatedRequest<{ items: Batch[] }>(withQuery(API_ENDPOINTS.academics.batches, { departmentId, status: "active", limit: 100 }))).data.items
  if (batchId) students = (await authenticatedRequest<StudentListData>(withQuery(API_ENDPOINTS.students.list, { academicBatchId: batchId, section: section || undefined, status: "active", page, limit: section ? 20 : 1 }))).data
  const selectedDepartment = departments.find((item) => item._id === departmentId); const selectedBatch = batches.find((item) => item._id === batchId)
  const href = (values: Record<string, string>) => `/dashboard/students/structure?${new URLSearchParams(values)}`
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Student organisation</p><h1 className="mt-1 text-3xl font-bold">Department → Batch → Section</h1><p className="mt-1 text-sm text-muted-foreground">Browse students through their canonical academic structure.</p></div><div className="flex gap-2"><Button variant="outline" render={<Link href="/dashboard/students" />}><List /> Table & ID search</Button><Button><FolderTree /> Structure view</Button></div></div>
    <div className="flex flex-wrap items-center gap-2 text-sm"><Link href="/dashboard/students/structure" className="rounded-lg bg-muted px-3 py-2 font-medium">Departments</Link>{selectedDepartment && <><span>›</span><Link href={href({ departmentId })} className="rounded-lg bg-muted px-3 py-2 font-medium">{selectedDepartment.code}</Link></>}{selectedBatch && <><span>›</span><Link href={href({ departmentId, batchId })} className="rounded-lg bg-muted px-3 py-2 font-medium">{selectedBatch.code}</Link></>}{section && <><span>›</span><span className="rounded-lg bg-primary px-3 py-2 font-medium text-primary-foreground">Section {section}</span></>}</div>
    {!departmentId && <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{departments.map((item) => <Link key={item._id} href={href({ departmentId: item._id })}><Card className="h-full transition hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-6"><Building2 className="size-6 text-primary" /><h2 className="mt-4 text-lg font-bold">{item.code}</h2><p className="text-sm text-muted-foreground">{item.name}</p><p className="mt-4 text-sm font-semibold text-primary">View batches →</p></CardContent></Card></Link>)}</section>}
    {departmentId && !batchId && <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{batches.map((item) => <Link key={item._id} href={href({ departmentId, batchId: item._id })}><Card className="h-full transition hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-6"><Users className="size-6 text-violet-600" /><h2 className="mt-4 text-lg font-bold">{item.code}</h2><p className="text-sm text-muted-foreground">{item.program.code} · {item.program.name}</p><p className="mt-4 text-sm font-semibold text-primary">View sections →</p></CardContent></Card></Link>)}{!batches.length && <p className="col-span-full rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No active batches found.</p>}</section>}
    {batchId && !section && <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{(students?.filters?.sections ?? []).map((item) => <Link key={item} href={href({ departmentId, batchId, section: item })}><Card className="h-full transition hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-6"><span className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-lg font-bold text-emerald-700">{item}</span><h2 className="mt-4 text-lg font-bold">Section {item}</h2><p className="mt-4 text-sm font-semibold text-primary">View students →</p></CardContent></Card></Link>)}{!students?.filters?.sections?.length && <p className="col-span-full rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No sections found in this batch.</p>}</section>}
    {section && <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Section {section} students</h2><Badge variant="secondary">{students?.pagination.total ?? 0} students</Badge></div>{students?.items.length ? <div className="overflow-hidden rounded-xl border bg-white"><Table><TableHeader><TableRow><TableHead>Student</TableHead><TableHead>Student ID</TableHead><TableHead>Program</TableHead><TableHead>Curriculum semester</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{students.items.map((student) => <TableRow key={student._id}><TableCell><div className="flex items-center gap-3"><Avatar className="size-9">{student.user.avatarUrl && <AvatarImage src={student.user.avatarUrl} alt={`${student.user.firstName} ${student.user.lastName}`} />}<AvatarFallback className="bg-blue-50 text-xs font-semibold text-blue-700">{student.user.firstName[0]}{student.user.lastName[0]}</AvatarFallback></Avatar><div><p className="font-medium">{student.user.firstName} {student.user.lastName}</p><p className="text-xs text-muted-foreground">Section {student.section}</p></div></div></TableCell><TableCell className="font-mono text-xs font-semibold">{student.studentId}</TableCell><TableCell><p className="font-medium">{student.program.code}</p><p className="max-w-52 truncate text-xs text-muted-foreground">{student.program.name}</p></TableCell><TableCell>Semester {student.currentSemesterNumber}</TableCell><TableCell><StudentStatusBadge status={student.status} /></TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" render={<Link href={`/dashboard/students/${student._id}`} />}>View</Button></TableCell></TableRow>)}</TableBody></Table><PaginationLinks pathname="/dashboard/students/structure" params={new URLSearchParams({ departmentId, batchId, section })} page={students.pagination.page} totalPages={students.pagination.totalPages} /></div> : <p className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No active students found in this section.</p>}</section>}
  </div>
}
