import { model, Schema } from "mongoose";

const studentSchema = new Schema(
  {
    user: { type: Schema.Types.ObjectId, ref: "User", required: true, unique: true, index: true },
    studentId: { type: String, required: true, unique: true, uppercase: true, trim: true, index: true },
    registrationNumber: { type: String, uppercase: true, trim: true, unique: true, sparse: true, maxlength: 60 },
    program: { type: Schema.Types.ObjectId, ref: "Program", required: true, index: true },
    admissionSemester: { type: Schema.Types.ObjectId, ref: "Semester", required: true, index: true },
    admissionApplication: { type: Schema.Types.ObjectId, ref: "Admission", unique: true, sparse: true },
    batch: { type: String, required: true, default: "Unassigned", trim: true, maxlength: 40, index: true },
    academicBatch: { type: Schema.Types.ObjectId, ref: "AcademicBatch", required: true, index: true },
    academicSection: { type: Schema.Types.ObjectId, ref: "AcademicSection", index: true },
    section: { type: String, required: true, default: "Unassigned", trim: true, maxlength: 20 },
    admissionDate: { type: Date },
    admissionType: { type: String, enum: ["regular", "transfer", "credit_transfer"], default: "regular" },
    academicSession: { type: String, trim: true, maxlength: 40 },
    campus: { type: String, trim: true, maxlength: 100 },
    studentCategory: { type: String, enum: ["regular", "improvement", "retake"], default: "regular" },
    assignedAdvisor: { type: Schema.Types.ObjectId, ref: "Teacher" },
    sectionTransfers: [{
      fromSection: { type: Schema.Types.ObjectId, ref: "AcademicSection" },
      toSection: { type: Schema.Types.ObjectId, ref: "AcademicSection", required: true },
      reason: { type: String, trim: true, maxlength: 300 },
      transferredBy: { type: Schema.Types.ObjectId, ref: "User", required: true },
      transferredAt: { type: Date, required: true, default: Date.now },
      _id: false,
    }],
    dateOfBirth: { type: Date },
    banglaName: { type: String, trim: true, maxlength: 160 },
    nationality: { type: String, trim: true, maxlength: 80 },
    religion: { type: String, trim: true, maxlength: 60 },
    bloodGroup: { type: String, enum: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"] },
    maritalStatus: { type: String, enum: ["single", "married", "other"] },
    nidNumber: { type: String, trim: true, maxlength: 30 },
    birthCertificateNumber: { type: String, trim: true, maxlength: 40 },
    passportNumber: { type: String, uppercase: true, trim: true, maxlength: 30 },
    gender: { type: String, enum: ["male", "female", "other", "prefer_not_to_say"] },
    phone: { type: String, trim: true, maxlength: 30 },
    alternatePhone: { type: String, trim: true, maxlength: 30 },
    universityEmail: { type: String, trim: true, lowercase: true, maxlength: 160 },
    guardian: {
      name: { type: String, trim: true, maxlength: 120 },
      relationship: { type: String, trim: true, maxlength: 60 },
      phone: { type: String, trim: true, maxlength: 30 },
      email: { type: String, trim: true, lowercase: true },
    },
    address: {
      line1: { type: String, trim: true },
      line2: { type: String, trim: true },
      city: { type: String, trim: true },
      state: { type: String, trim: true },
      country: { type: String, trim: true },
      postalCode: { type: String, trim: true },
    },
    permanentAddress: {
      line1: { type: String, trim: true }, line2: { type: String, trim: true }, city: { type: String, trim: true },
      state: { type: String, trim: true }, country: { type: String, trim: true }, postalCode: { type: String, trim: true },
    },
    parents: {
      father: { name: { type: String, trim: true }, profession: { type: String, trim: true }, phone: { type: String, trim: true } },
      mother: { name: { type: String, trim: true }, profession: { type: String, trim: true }, phone: { type: String, trim: true } },
    },
    previousEducation: [{
      level: { type: String, required: true, trim: true }, institution: { type: String, required: true, trim: true },
      board: { type: String, trim: true }, result: { type: String, required: true, trim: true }, passingYear: { type: Number, required: true, min: 1950, max: 2200 },
      rollNumber: { type: String, trim: true }, registrationNumber: { type: String, trim: true }, _id: false,
    }],
    documents: [{
      type: { type: String, required: true, trim: true }, url: { type: String, required: true, trim: true },
      status: { type: String, enum: ["pending", "verified", "rejected"], default: "pending" },
      verifiedAt: { type: Date }, verifiedBy: { type: Schema.Types.ObjectId, ref: "User" }, _id: false,
    }],
    waiverCategory: { type: String, trim: true, maxlength: 80 },
    residentialStatus: { type: String, enum: ["day_scholar", "hostel", "other"], default: "day_scholar" },
    hostelRequired: { type: Boolean, default: false },
    transportRequired: { type: Boolean, default: false },
    administrativeNotes: { type: String, trim: true, maxlength: 2000 },
    currentSemesterNumber: { type: Number, min: 1, default: 1 },
    status: {
      type: String,
      enum: ["active", "graduated", "suspended", "withdrawn", "archived"],
      default: "active",
      index: true,
    },
  },
  { timestamps: true, versionKey: false },
);

studentSchema.index({ program: 1, status: 1 });
studentSchema.index({ program: 1, batch: 1, status: 1 });
export const StudentModel = model("Student", studentSchema);
